{
 "title": "NBomber",
 "time": { "from": "2023-02-02T12:52:22.944Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "session_id", "label": "session id" },
   {
    "name": "test_suite",
    "label": "test suite",
    "query": "SHOW TAG VALUES with KEY = \"test_suite\""
   },
   {
    "name": "test_name",
    "label": "test name",
    "query": "SHOW TAG VALUES with KEY = \"test_name\" WHERE test_suite =~ /^$test_suite$/"
   },
   { "name": "current_operation", "label": "current operation", "query": "warmup, bombing, complete" },
   {
    "name": "scenario",
    "label": "scenario",
    "query": "SHOW TAG VALUES with KEY = \"scenario\" WHERE test_suite =~ /^$test_suite$/ AND test_name =~ /^$test_name$/"
   },
   {
    "name": "step",
    "label": "step",
    "query": "SHOW TAG VALUES with KEY = \"step\" WHERE test_suite =~ /^$test_suite$/ AND test_name =~ /^$test_name$/ AND scenario =~ /^$scenario$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT sum(\"cluster.node_cpu_count\") as \"cpu count\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"current_operation\" = 'bombing') GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "cluster_node" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "scenario status codes",
   "type": "table",
   "description": "It displays stats only for current_operation = complete",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "nbomber",
     "query": "SELECT last(\"status_code.count\") as \"count\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"current_operation\" = 'complete') GROUP BY time(1d), \"scenario\", \"status_code.status\"",
     "select": [
      [
       { "params": [ "status_code.count" ], "type": "field" }
      ],
      [
       { "params": [ "status_code.is_error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  { "title": "$scenario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "scenario" },
  {
   "title": "OK Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"simulation.value\") as \"load value\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"ok.request.count\") as \"request count\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.request.rps\") as \"rps\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.min\") as \"min\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.mean\") as \"mean\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.max\") as \"max\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent50\") as \"p50\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent75\") as \"p75\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent95\") as \"p95\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent99\") as \"p99\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.stddev\") as \"stddev\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.datatransfer.min\") as \"data_min\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.datatransfer.mean\") as \"data_mean\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1m), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.datatransfer.max\") as \"data_max\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1m), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.datatransfer.all\") as \"data_all\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1m), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "ok RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.request.rps\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fail RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.request.rps\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"simulation.value\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scenario latency indicators",
   "type": "bargauge",
   "description": "It displays stats only for current_operation = complete",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "t <= 800",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.less_or_eq_800\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"current_operation\" = 'complete') GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "latency_count.less_or_eq_800" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "t > 800 and t < 1200",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.more_800_less_1200\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"current_operation\" = 'complete') GROUP BY time(1d)",
     "select": [
      [
       {
        "params": [
         "latency_count.more_800_less_1200"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    },
    {
     "alias": "t >= 1200",
     "measurement": "nbomber",
     "query": "SELECT last(\"latency_count.more_or_eq_1200\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"current_operation\" = 'complete') GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "latency_count.more_or_eq_1200" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "test_suite", "operator": "=~", "value": "/^$test_suite$/" },
      { "condition": "AND", "key": "test_name", "operator": "=~", "value": "/^$test_name$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "step", "operator": "=~", "value": "/^$step$/" },
      { "condition": "AND", "key": "operation", "operator": "=", "value": "complete" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.min\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.max\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "p50",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent50\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "p99",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ok.latency.percent99\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "alias": "ok RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nbomber",
     "query": "SELECT last(\"ok.request.rps\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fail RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.request.rps\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"simulation.value\") FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" = 'global information' AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAIL Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"fail.request.count\") as \"request count\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.request.rps\") as \"rps\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.min\") as \"min\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.mean\") as \"mean\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.max\") as \"max\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.percent50\") as \"p50\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.percent75\") as \"p75\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.percent95\") as \"p95\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.percent99\") as \"p99\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.latency.stddev\") as \"stddev\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.datatransfer.min\") as \"data_min\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.datatransfer.mean\") as \"data_mean\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.datatransfer.max\") as \"data_max\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"fail.datatransfer.all\") as \"data_all\" FROM \"nbomber\" WHERE (\"session_id\" =~ /^$session_id$/ AND \"test_suite\" =~ /^$test_suite$/ AND \"test_name\" =~ /^$test_name$/ AND \"scenario\" =~ /^$scenario$/ AND \"step\" =~ /^$step$/ AND \"current_operation\" =~ /^$current_operation$/) AND $timeFilter GROUP BY time(1d), \"step\", \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}